name: Sandbox/Mulesoft - Build and Deploy

on: 
  workflow_dispatch:

env:
          
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
         
jobs:
 

  Build:

       runs-on: ubuntu-latest
       permissions:
        contents: read
        packages: write
       steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
              java-version: '11'
              distribution: 'temurin'
              server-id: github 
              settings-path: ${{ github.workspace }} 
              
          - name: Build with Maven
            run: mvn -B package --file pom.xml

          - name: Publish to GitHub Packages Apache Maven
            run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
            
                     
  Sonar:
  
    needs: [Build]
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      - name: Sonar Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=shiyamsundark_customer-account-records -Dsonar.organization=shiyamsundark -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        
  Deploy:
  
    needs: [Build,Sonar]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Deploy to Sandbox
        
          run: |
      
           mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Danypoint.username="$USERNAME" \
           -Danypoint.password="$PASSWORD" \
           -DskipTests
